import { useNavigate } from 'react-router-dom'
import { useState, useEffect } from 'react'
import './Landing.css'

const DOCS = [
  {
    id: 'privacy-policy',
    icon: '🔒',
    name: 'Privacy Policy',
    desc: 'Required for any app, website or service that collects user data.',
    time: '2 min',
    popular: true,
  },
  {
    id: 'terms-of-service',
    icon: '📋',
    name: 'Terms of Service',
    desc: 'Define the rules users must agree to when using your product.',
    time: '2 min',
    popular: true,
  },
  {
    id: 'nda',
    icon: '🤝',
    name: 'Non-Disclosure Agreement',
    desc: 'Protect confidential information shared with employees or partners.',
    time: '3 min',
    popular: false,
  },
  {
    id: 'freelance-contract',
    icon: '✍️',
    name: 'Freelance Contract',
    desc: 'Set expectations, deliverables, and payment terms for client work.',
    time: '3 min',
    popular: false,
  },
  {
    id: 'independent-contractor',
    icon: '🏢',
    name: 'Independent Contractor Agreement',
    desc: 'Formally define the relationship between your business and contractors.',
    time: '3 min',
    popular: false,
  },
]

const TICKER_ITEMS = [
  'Privacy Policies', 'NDAs', 'Freelance Contracts', 'Terms of Service',
  'Contractor Agreements',
]

const FAQS = [
  {
    q: 'Is this document legally binding?',
    a: 'Yes — documents generated by Signova are based on real legal frameworks and established templates used by attorneys. They are enforceable in most jurisdictions. For high-stakes matters (litigation, complex IP, employment disputes), we recommend having an attorney review the final document.',
  },
  {
    q: 'What file format do I receive?',
    a: 'You get a clean PDF generated via your browser\'s print function. The formatting is professional and print-ready. You can also copy the text into any word processor (Google Docs, Word) to edit further.',
  },
  {
    q: 'Can I edit the document after downloading?',
    a: 'Absolutely. The PDF is yours to keep and use however you need. Copy the text into a word processor to make edits, add your signature, or reformat it for your branding.',
  },
  {
    q: 'What countries and jurisdictions are supported?',
    a: 'Signova generates documents suitable for use in the US, UK, Canada, Australia, and most other common-law countries. During generation you can specify your jurisdiction so the document is tailored accordingly.',
  },
  {
    q: 'Is my information stored or shared?',
    a: 'No. Your answers are used only to generate your document in real time — they are never saved to a database, logged, or shared with third parties. Once you close the tab, the data is gone.',
  },
  {
    q: 'What if I\'m not happy with the result?',
    a: 'You can preview your complete document for free before paying anything. If after downloading you\'re not satisfied, email us at hello@getsignova.com and we\'ll make it right.',
  },
]

export default function Landing() {
  const navigate = useNavigate()
  const [ticker, setTicker] = useState(0)
  const [tickerVisible, setTickerVisible] = useState(true)
  const [navOpen, setNavOpen] = useState(false)
  const [openFaq, setOpenFaq] = useState(null)
  const [waitlistEmail, setWaitlistEmail] = useState('')
  const [waitlistSubmitted, setWaitlistSubmitted] = useState(false)

  useEffect(() => {
    const t = setInterval(() => {
      setTickerVisible(false)
      setTimeout(() => {
        setTicker(p => (p + 1) % TICKER_ITEMS.length)
        setTickerVisible(true)
      }, 300)
    }, 2500)
    return () => clearInterval(t)
  }, [])

  const closeNav = () => setNavOpen(false)

  const handleWaitlist = (e) => {
    e.preventDefault()
    if (waitlistEmail.trim()) setWaitlistSubmitted(true)
  }

  return (
    <div className="landing">
      <nav className="nav">
        <div className="nav-inner">
          <div className="logo">
            <span className="logo-mark">S</span>
            <span className="logo-text">Signova</span>
          </div>
          <div className={`nav-links ${navOpen ? 'open' : ''}`}>
            <a href="#documents" onClick={closeNav}>Documents</a>
            <a href="#how" onClick={closeNav}>How it works</a>
            <a href="#pricing" onClick={closeNav}>Pricing</a>
            <a href="#faq" onClick={closeNav}>FAQ</a>
          </div>
          <button
            className="hamburger"
            onClick={() => setNavOpen(o => !o)}
            aria-label="Toggle menu"
          >
            <span className={`ham-line ${navOpen ? 'open' : ''}`} />
            <span className={`ham-line ${navOpen ? 'open' : ''}`} />
            <span className={`ham-line ${navOpen ? 'open' : ''}`} />
          </button>
        </div>
      </nav>

      <section className="hero">
        <div className="hero-glow" />
        <div className="hero-inner">
          <div className="hero-badge">
            <span className="badge-dot" />
            AI-Powered · No Account Required · First Document Free
          </div>
          <h1 className="hero-title">
            Generate professional
            <br />
            <span className={`hero-accent ${tickerVisible ? 'visible' : ''}`}>
              {TICKER_ITEMS[ticker]}
            </span>
            <br />
            in under 3 minutes.
          </h1>
          <p className="hero-sub">
            Stop paying $300/hr for standard legal documents. Answer a few questions,
            get a lawyer-quality document instantly. Preview free, pay $4.99 to download.
          </p>
          <div className="hero-actions">
            <button
              className="btn-primary"
              onClick={() => document.getElementById('documents').scrollIntoView({ behavior: 'smooth' })}
            >
              Generate your document
              <span className="btn-arrow">→</span>
            </button>
            <span className="hero-note">No credit card · No account · First preview free</span>
          </div>
          <div className="hero-stats">
            <div className="stat"><span className="stat-num">5</span><span className="stat-label">Document types</span></div>
            <div className="stat-div" />
            <div className="stat"><span className="stat-num">~2 min</span><span className="stat-label">Average time</span></div>
            <div className="stat-div" />
            <div className="stat"><span className="stat-num">$4.99</span><span className="stat-label">Per document</span></div>
          </div>
        </div>
      </section>

      <section className="docs-section" id="documents">
        <div className="section-inner">
          <div className="section-header">
            <p className="section-label">Choose your document</p>
            <h2 className="section-title">What do you need today?</h2>
          </div>
          <div className="docs-grid">
            {DOCS.map(doc => (
              <button key={doc.id} className="doc-card" onClick={() => navigate(`/generate/${doc.id}`)}>
                {doc.popular && <span className="doc-popular">Popular</span>}
                <div className="doc-icon">{doc.icon}</div>
                <div className="doc-content">
                  <h3 className="doc-name">{doc.name}</h3>
                  <p className="doc-desc">{doc.desc}</p>
                </div>
                <div className="doc-footer">
                  <span className="doc-time">⏱ {doc.time}</span>
                  <span className="doc-price">$4.99</span>
                  <span className="doc-go">Generate →</span>
                </div>
              </button>
            ))}
          </div>
        </div>
      </section>

      <section className="how-section" id="how">
        <div className="section-inner">
          <div className="section-header">
            <p className="section-label">The process</p>
            <h2 className="section-title">Three steps to done.</h2>
          </div>
          <div className="steps">
            {[
              { n: '01', title: 'Choose your document', body: 'Select from Privacy Policy, Terms of Service, NDA, Freelance Contract, or Independent Contractor Agreement.' },
              { n: '02', title: 'Answer a few questions', body: 'Tell us about your business, jurisdiction, and needs. Takes about 2 minutes. No legal knowledge required.' },
              { n: '03', title: 'Preview free, pay to download', body: 'See your complete document instantly. Pay $4.99 to download the clean, watermark-free PDF.' },
            ].map(s => (
              <div key={s.n} className="step">
                <span className="step-num">{s.n}</span>
                <div>
                  <h3 className="step-title">{s.title}</h3>
                  <p className="step-body">{s.body}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="pricing-section" id="pricing">
        <div className="section-inner">
          <div className="section-header">
            <p className="section-label">Pricing</p>
            <h2 className="section-title">Simple and honest.</h2>
          </div>
          <div className="pricing-grid">
            <div className="price-card">
              <div className="price-tier">Free Preview</div>
              <div className="price-amount">$0</div>
              <p className="price-desc">See your complete document before paying anything.</p>
              <ul className="price-list">
                <li className="price-yes">✓ Full document generated</li>
                <li className="price-yes">✓ Preview in browser</li>
                <li className="price-yes">✓ No account needed</li>
                <li className="price-no">✗ Watermarked PDF</li>
                <li className="price-no">✗ No download</li>
              </ul>
              <button
                className="btn-outline"
                onClick={() => document.getElementById('documents').scrollIntoView({ behavior: 'smooth' })}
              >
                Try for free
              </button>
            </div>

            <div className="price-card price-featured">
              <div className="price-top-badge">Most popular</div>
              <div className="price-tier">Single Document</div>
              <div className="price-amount">$4.99</div>
              <p className="price-desc">Pay once, download once. Clean PDF, yours to keep.</p>
              <ul className="price-list">
                <li className="price-yes">✓ Full document generated</li>
                <li className="price-yes">✓ Clean PDF, no watermark</li>
                <li className="price-yes">✓ Instant download</li>
                <li className="price-yes">✓ Legally reviewed templates</li>
                <li className="price-yes">✓ No subscription</li>
              </ul>
              <button
                className="btn-primary"
                onClick={() => document.getElementById('documents').scrollIntoView({ behavior: 'smooth' })}
              >
                Get started <span className="btn-arrow">→</span>
              </button>
            </div>

            <div className="price-card">
              <div className="price-tier">Unlimited</div>
              <div className="price-amount">$9.99<span className="price-per">/mo</span></div>
              <p className="price-desc">For freelancers and growing businesses. Coming soon.</p>
              <ul className="price-list">
                <li className="price-yes">✓ Unlimited documents</li>
                <li className="price-yes">✓ All document types</li>
                <li className="price-yes">✓ Clean PDFs always</li>
                <li className="price-yes">✓ Priority generation</li>
                <li className="price-yes">✓ Cancel anytime</li>
              </ul>
              {waitlistSubmitted ? (
                <div className="waitlist-submitted">
                  You're on the list! We'll email you when Unlimited launches.
                </div>
              ) : (
                <form className="waitlist-form" onSubmit={handleWaitlist}>
                  <input
                    className="waitlist-input"
                    type="email"
                    placeholder="your@email.com"
                    value={waitlistEmail}
                    onChange={e => setWaitlistEmail(e.target.value)}
                    required
                  />
                  <button type="submit" className="btn-outline waitlist-btn">
                    Notify me when available
                  </button>
                </form>
              )}
            </div>
          </div>
        </div>
      </section>

      <section className="faq-section" id="faq">
        <div className="section-inner">
          <div className="section-header">
            <p className="section-label">Questions</p>
            <h2 className="section-title">Everything you need to know.</h2>
          </div>
          <div className="faq-list">
            {FAQS.map((item, i) => (
              <div key={i} className={`faq-item ${openFaq === i ? 'open' : ''}`}>
                <button
                  className="faq-question"
                  onClick={() => setOpenFaq(openFaq === i ? null : i)}
                >
                  <span>{item.q}</span>
                  <span className="faq-icon">{openFaq === i ? '−' : '+'}</span>
                </button>
                <div className="faq-answer">
                  <p>{item.a}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="trust-section">
        <div className="section-inner">
          <div className="trust-grid">
            {[
              { icon: '⚡', title: 'Instant generation', body: 'Documents ready in seconds, not days.' },
              { icon: '🔐', title: 'Privacy first', body: 'Your answers are never stored or shared.' },
              { icon: '📄', title: 'Lawyer-reviewed', body: 'Templates built from real legal frameworks.' },
              { icon: '🌍', title: 'Jurisdiction-aware', body: 'Tailored for your country and industry.' },
            ].map(t => (
              <div key={t.title} className="trust-item">
                <span className="trust-icon">{t.icon}</span>
                <h3 className="trust-title">{t.title}</h3>
                <p className="trust-body">{t.body}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="cta-section">
        <div className="section-inner">
          <div className="cta-box">
            <h2 className="cta-title">Ready to get protected?</h2>
            <p className="cta-sub">Your first document preview is completely free. No credit card, no account.</p>
            <button
              className="btn-primary btn-large"
              onClick={() => document.getElementById('documents').scrollIntoView({ behavior: 'smooth' })}
            >
              Generate your document now <span className="btn-arrow">→</span>
            </button>
          </div>
        </div>
      </section>

      <footer className="footer">
        <div className="footer-inner">
          <div className="logo">
            <span className="logo-mark">S</span>
            <span className="logo-text">Signova</span>
          </div>
          <div className="footer-links">
            <a href="/privacy">Privacy Policy</a>
            <a href="/terms">Terms of Use</a>
            <a href="mailto:hello@getsignova.com">Contact</a>
          </div>
          <p className="footer-disc">
            Documents generated by Signova are based on legal templates and AI assistance.
            For complex legal matters, consult a qualified attorney.
          </p>
          <p className="footer-copy">© 2026 Signova · Ebenova Solutions</p>
        </div>
      </footer>
    </div>
  )
}
