import { useNavigate } from 'react-router-dom'
import { useEffect, useState, useRef } from 'react'
import './Preview.css'


export default function Preview() {
  const navigate = useNavigate()
  const [doc, setDoc] = useState(null)
  const [paying, setPaying] = useState(false)
  const [paid, setPaid] = useState(false)
  const [verifying, setVerifying] = useState(false)
  const [error, setError] = useState('')
  const contentRef = useRef(null)

  useEffect(() => {
    const raw = sessionStorage.getItem('signova_doc')
    if (!raw) { navigate('/'); return }
    setDoc(JSON.parse(raw))
    window.scrollTo(0, 0)
  }, [])

  const handleDownload = async () => {
    if (paid) { downloadPDF(); return }
    setPaying(true)
    setError('')
    try {
      const res = await fetch('/api/checkout', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ docType: doc.docType, docName: doc.docName }),
      })
      if (!res.ok) throw new Error('Could not start checkout. Please try again.')
      const { url } = await res.json()
      window.location.href = url
    } catch (e) {
      setError(e.message)
      setPaying(false)
    }
  }

  const downloadPDF = async () => {
    // Simple print-to-PDF approach
    const content = doc.content
    const printWindow = window.open('', '_blank')

    // Mobile browsers (iOS Safari) often block window.open in async context
    if (!printWindow) {
      // Fallback: write to current window in a printable overlay
      const blob = new Blob([`<!DOCTYPE html><html><head><title>${doc.docName} — Signova</title><style>body{font-family:Georgia,serif;font-size:12px;line-height:1.8;color:#111;max-width:700px;margin:40px auto;padding:0 40px}h1{font-size:22px}h2{font-size:16px;margin-top:28px}h3{font-size:14px;margin-top:20px}p{margin-bottom:12px}.footer{margin-top:60px;padding-top:20px;border-top:1px solid #ddd;font-size:10px;color:#888;text-align:center}@media print{body{margin:0}}</style></head><body>${content.replace(/\n/g, '<br>').replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')}<div class="footer">Generated by Signova · getsignova.com</div></body></html>`], { type: 'text/html' })
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `${doc.docName.replace(/\s+/g, '_')}_Signova.html`
      a.click()
      URL.revokeObjectURL(url)
      return
    }

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>${doc.docName} — Signova</title>
        <style>
          body { font-family: Georgia, serif; font-size: 12px; line-height: 1.8; color: #111; max-width: 700px; margin: 40px auto; padding: 0 40px; }
          h1 { font-size: 22px; margin-bottom: 8px; }
          h2 { font-size: 16px; margin-top: 28px; margin-bottom: 8px; }
          h3 { font-size: 14px; margin-top: 20px; }
          p { margin-bottom: 12px; }
          .footer { margin-top: 60px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 10px; color: #888; text-align: center; }
          @media print { body { margin: 0; } }
        </style>
      </head>
      <body>
        ${content.replace(/\n/g, '<br>').replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')}
        <div class="footer">Generated by Signova · getsignova.com</div>
      </body>
      </html>
    `)
    printWindow.document.close()
    printWindow.print()
  }

  // Check if returning from Polar payment success
  // Verify the payment server-side, then regenerate with Anthropic
  useEffect(() => {
    const params = new URLSearchParams(window.location.search)
    if (params.get('payment') !== 'success') return

    const checkoutId = params.get('checkout_id')
    if (!checkoutId) {
      console.error('No checkout_id in return URL')
      setError('Payment could not be verified — missing checkout reference. Please contact hello@getsignova.com.')
      return
    }

    const raw = sessionStorage.getItem('signova_doc')
    if (!raw) return
    const savedDoc = JSON.parse(raw)

    setVerifying(true)

    const verifyAndRegenerate = async () => {
      try {
        // Step 1: Verify payment server-side
        const verifyRes = await fetch('/api/verify-payment', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ checkoutId }),
        })

        const verifyData = await verifyRes.json()

        if (!verifyRes.ok || !verifyData.verified) {
          console.error('Payment verification failed:', verifyData)
          setError('Payment could not be verified. If you were charged, please contact hello@getsignova.com with your checkout reference.')
          setVerifying(false)
          return
        }

        // Step 2: Payment verified — regenerate with Anthropic (premium)
        if (savedDoc.prompt) {
          try {
            const genRes = await fetch('/api/generate', {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify({ prompt: savedDoc.prompt, checkoutId }),
            })

            if (genRes.ok) {
              const genData = await genRes.json()
              if (genData.text) {
                const upgraded = { ...savedDoc, content: genData.text, isPremium: true, checkoutId }
                sessionStorage.setItem('signova_doc', JSON.stringify(upgraded))
                setDoc(upgraded)
              }
            } else {
              console.warn('Premium regeneration failed, using preview version')
            }
          } catch (genErr) {
            console.error('Premium regeneration error:', genErr)
            // Still mark as paid — they paid, let them download the preview version
          }
        }

        setPaid(true)

        // Clean up URL params so refreshing doesn't re-verify
        window.history.replaceState({}, '', '/preview')
      } catch (err) {
        console.error('Verification error:', err)
        setError('Something went wrong verifying your payment. Please contact hello@getsignova.com.')
      } finally {
        setVerifying(false)
      }
    }

    verifyAndRegenerate()
  }, [])

  if (!doc) return (
    <div className="preview-loading">
      <div className="spinner-large" />
      <p>Loading your document…</p>
    </div>
  )

  if (verifying) return (
    <div className="preview-loading">
      <div className="spinner-large" />
      <p>Verifying your payment…</p>
    </div>
  )

  const lines = doc.content.split('\n')

  return (
    <div className="preview-page">
      {/* Nav */}
      <div className="preview-nav">
        <button className="gen-back" onClick={() => navigate('/')}>← Back to home</button>
        <div className="logo">
          <span className="logo-mark">S</span>
          <span className="logo-text">Signova</span>
        </div>
        <div className="preview-nav-right">
          {paid ? (
            <button className="btn-download" onClick={downloadPDF}>
              ⬇ Download PDF
            </button>
          ) : (
            <button className="btn-pay" onClick={handleDownload} disabled={paying}>
              {paying ? <><span className="spinner-sm" /> Processing…</> : <>Download PDF — $4.99</>}
            </button>
          )}
        </div>
      </div>

      <div className="preview-layout">
        {/* Document */}
        <div className="preview-doc-wrap">
          {!paid && (
            <div className="preview-watermark-bar">
              🔒 Preview only — <button onClick={handleDownload} disabled={paying}>Pay $4.99 to download the clean PDF</button>
            </div>
          )}
          {paid && (
            <div className="preview-paid-bar">
              ✓ Payment confirmed — your document is ready to download
            </div>
          )}

          <div className={`preview-doc ${!paid ? 'watermarked' : ''}`} ref={contentRef}>
            {!paid && <div className="watermark-overlay"><span>PREVIEW ONLY · SIGNOVA</span></div>}
            <div className="doc-content">
              {lines.map((line, i) => {
                if (!line.trim()) return <br key={i} />
                // Bold markdown
                const formatted = line.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
                if (line.startsWith('# ')) return <h1 key={i} dangerouslySetInnerHTML={{ __html: formatted.slice(2) }} />
                if (line.startsWith('## ')) return <h2 key={i} dangerouslySetInnerHTML={{ __html: formatted.slice(3) }} />
                if (line.startsWith('### ')) return <h3 key={i} dangerouslySetInnerHTML={{ __html: formatted.slice(4) }} />
                return <p key={i} dangerouslySetInnerHTML={{ __html: formatted }} />
              })}
            </div>
          </div>
        </div>

        {/* Sidebar */}
        <div className="preview-sidebar">
          <div className="sidebar-card">
            <h3 className="sidebar-title">Your document is ready</h3>
            <p className="sidebar-body">
              Preview your complete {doc.docName} below.
              Pay once to download the clean, watermark-free PDF.
            </p>
            <div className="sidebar-price">
              <span className="price-big">$4.99</span>
              <span className="price-label">one-time download</span>
            </div>
            {error && <div className="sidebar-error">{error}</div>}
            {paid ? (
              <button className="btn-download-full" onClick={downloadPDF}>
                ⬇ Download clean PDF
              </button>
            ) : (
              <button className="btn-pay-full" onClick={handleDownload} disabled={paying}>
                {paying
                  ? <><span className="spinner-sm" /> Processing…</>
                  : <>Pay $4.99 &amp; Download →</>
                }
              </button>
            )}
            <ul className="sidebar-perks">
              <li>✓ Clean PDF, no watermark</li>
              <li>✓ Instant download</li>
              <li>✓ Yours to keep forever</li>
            </ul>

            {/* WhatsApp fallback for Nigeria / Africa / Asia */}
            {!paid && (
              <div className="sidebar-whatsapp">
                <p className="wa-label">Card not working?</p>
                <a
                  href="https://wa.me/14032742793?text=Hi%2C%20I%20want%20to%20pay%20for%20a%20Signova%20document%20via%20bank%20transfer"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="btn-whatsapp"
                >
                  💬 Pay via WhatsApp
                </a>
                <p className="wa-sub">Bank transfer available for Nigeria &amp; Africa</p>
              </div>
            )}
          </div>

          <div className="sidebar-need-more">
            <p>Need multiple documents?</p>
            <strong>Unlimited plan — $9.99/month</strong>
            <button className="btn-unlimited" onClick={() => navigate('/#pricing')}>
              View unlimited plan
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
