import { useNavigate } from 'react-router-dom'
import { useEffect, useState, useRef } from 'react'
import './Preview.css'


export default function Preview() {
  const navigate = useNavigate()
  const [doc, setDoc] = useState(null)
  const [paying, setPaying] = useState(false)
  const [paid, setPaid] = useState(false)
  const [error, setError] = useState('')
  const contentRef = useRef(null)

  useEffect(() => {
    const raw = sessionStorage.getItem('signova_doc')
    if (!raw) { navigate('/'); return }
    setDoc(JSON.parse(raw))
  }, [])

  const handleDownload = async () => {
    if (paid) { downloadPDF(); return }
    setPaying(true)
    setError('')
    try {
      const res = await fetch('/api/checkout', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ docType: doc.docType, docName: doc.docName }),
      })
      if (!res.ok) throw new Error('Could not start checkout. Please try again.')
      const { url } = await res.json()
      window.location.href = url
    } catch (e) {
      setError(e.message)
      setPaying(false)
    }
  }

  const downloadPDF = async () => {
    // Simple print-to-PDF approach
    const content = doc.content
    const printWindow = window.open('', '_blank')
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>${doc.docName} — Signova</title>
        <style>
          body { font-family: Georgia, serif; font-size: 12px; line-height: 1.8; color: #111; max-width: 700px; margin: 40px auto; padding: 0 40px; }
          h1 { font-size: 22px; margin-bottom: 8px; }
          h2 { font-size: 16px; margin-top: 28px; margin-bottom: 8px; }
          h3 { font-size: 14px; margin-top: 20px; }
          p { margin-bottom: 12px; }
          .footer { margin-top: 60px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 10px; color: #888; text-align: center; }
        </style>
      </head>
      <body>
        ${content.replace(/\n/g, '<br>').replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')}
        <div class="footer">Generated by Signova · getsignova.com</div>
      </body>
      </html>
    `)
    printWindow.document.close()
    printWindow.print()
  }

  // Check if returning from Lemon Squeezy success
  useEffect(() => {
    const params = new URLSearchParams(window.location.search)
    if (params.get('payment') === 'success') {
      setPaid(true)
    }
  }, [])

  if (!doc) return (
    <div className="preview-loading">
      <div className="spinner-large" />
      <p>Loading your document…</p>
    </div>
  )

  const lines = doc.content.split('\n')

  return (
    <div className="preview-page">
      {/* Nav */}
      <div className="preview-nav">
        <button className="gen-back" onClick={() => navigate('/')}>← Back to home</button>
        <div className="logo">
          <span className="logo-mark">S</span>
          <span className="logo-text">Signova</span>
        </div>
        <div className="preview-nav-right">
          {paid ? (
            <button className="btn-download" onClick={downloadPDF}>
              ⬇ Download PDF
            </button>
          ) : (
            <button className="btn-pay" onClick={handleDownload} disabled={paying}>
              {paying ? <><span className="spinner-sm" /> Processing…</> : <>Download PDF — $4.99</>}
            </button>
          )}
        </div>
      </div>

      <div className="preview-layout">
        {/* Document */}
        <div className="preview-doc-wrap">
          {!paid && (
            <div className="preview-watermark-bar">
              🔒 Preview only — <button onClick={handleDownload} disabled={paying}>Pay $4.99 to download the clean PDF</button>
            </div>
          )}
          {paid && (
            <div className="preview-paid-bar">
              ✓ Payment confirmed — your document is ready to download
            </div>
          )}
          <div className="preview-disclaimer">
            ⚖️ <strong>Not legal advice.</strong> This document is an AI-generated starting point. Signova is not a law firm and no attorney-client relationship is created. Review with a qualified attorney before signing or relying on this document.
          </div>
          <div className={`preview-doc ${!paid ? 'watermarked' : ''}`} ref={contentRef}>
            {!paid && <div className="watermark-overlay"><span>PREVIEW ONLY · SIGNOVA</span></div>}
            <div className="doc-content">
              {lines.map((line, i) => {
                if (!line.trim()) return <br key={i} />
                // Bold markdown
                const formatted = line.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
                if (line.startsWith('# ')) return <h1 key={i} dangerouslySetInnerHTML={{ __html: formatted.slice(2) }} />
                if (line.startsWith('## ')) return <h2 key={i} dangerouslySetInnerHTML={{ __html: formatted.slice(3) }} />
                if (line.startsWith('### ')) return <h3 key={i} dangerouslySetInnerHTML={{ __html: formatted.slice(4) }} />
                return <p key={i} dangerouslySetInnerHTML={{ __html: formatted }} />
              })}
            </div>
          </div>
        </div>

        {/* Sidebar */}
        <div className="preview-sidebar">
          <div className="sidebar-card">
            <h3 className="sidebar-title">Your document is ready</h3>
            <p className="sidebar-body">
              Preview your complete {doc.docName} below.
              Pay once to download the clean, watermark-free PDF.
            </p>
            <div className="sidebar-price">
              <span className="price-big">$4.99</span>
              <span className="price-label">one-time download</span>
            </div>
            {error && <div className="sidebar-error">{error}</div>}
            {paid ? (
              <button className="btn-download-full" onClick={downloadPDF}>
                ⬇ Download clean PDF
              </button>
            ) : (
              <button className="btn-pay-full" onClick={handleDownload} disabled={paying}>
                {paying
                  ? <><span className="spinner-sm" /> Processing…</>
                  : <>Pay $4.99 &amp; Download →</>
                }
              </button>
            )}
            <ul className="sidebar-perks">
              <li>✓ Clean PDF, no watermark</li>
              <li>✓ Instant download</li>
              <li>✓ Yours to keep forever</li>
            </ul>
          </div>

          <div className="sidebar-need-more">
            <p>Need multiple documents?</p>
            <strong>Unlimited plan — $9.99/month</strong>
            <button className="btn-unlimited" onClick={() => navigate('/#pricing')}>
              View unlimited plan
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
