import { useNavigate } from 'react-router-dom'
import { Helmet } from 'react-helmet-async'
import './LegalPage.css'

export default function TermsPage() {
  const navigate = useNavigate()
  return (
    <div className="legal-page">
      <Helmet>
        <title>Terms of Use | Signova</title>
        <meta name="description" content="Signova terms of use — understand your rights when generating legal documents with our AI service." />
        <link rel="canonical" href="https://www.getsignova.com/terms" />
      </Helmet>
      <nav className="legal-nav">
        <button className="legal-back" onClick={() => navigate('/')}>← Back to Signova</button>
        <div className="logo">
          <span className="logo-mark">S</span>
          <span className="logo-text">Signova</span>
        </div>
      </nav>
      <div className="legal-body">
        <h1>Terms of Use</h1>
        <p className="legal-date">Last updated: March 2026</p>

        <p style={{ background: '#1a1a1a', border: '1px solid #333', borderRadius: '8px', padding: '14px 18px', fontSize: '14px', color: '#c8c4bc' }}>
          <strong>Using the Vigil Fraud Alert API?</strong> Vigil has additional terms
          covering card data, GPS consent, AI decisioning, and acceptable use. See the
          <a href="/vigil/terms" style={{ color: '#c9a84c', marginLeft: 4 }}>Vigil Terms Addendum</a>.
        </p>

        <h2>1. Acceptance</h2>
        <p>By using Signova ("the Service"), you agree to these Terms. If you do not agree, do not use the Service.</p>

        <h2>2. Not legal advice</h2>
        <p>Documents generated by Signova are produced by an AI system using legal templates. They are intended as a starting point and general reference — not as legal advice. Signova is not a law firm and does not have an attorney-client relationship with you. For specific legal questions or high-stakes matters, consult a qualified attorney.</p>

        <h2>3. Your document, your responsibility</h2>
        <p>Once you download a document, you are responsible for reviewing it and determining whether it meets your needs. Signova makes no warranties, express or implied, regarding the fitness of any generated document for a particular legal purpose or jurisdiction.</p>

        <h2>4. Purchases and refunds</h2>
        <p>Each document purchase is a one-time payment of $4.99. Because you can preview the full document before purchasing, all sales are final. If you experience a technical issue that prevented you from accessing your download, contact us at <a href={`mailto:${'info'}@${'ebenova.net'}`}>
          <span className="email-obfuscated" data-user="info" data-domain="ebenova.net"></span>
        </a> within 7 days and we will resolve it.</p>

        <h2>5. Permitted use</h2>
        <p>You may use documents generated by Signova for your own personal or business purposes. You may not resell, sublicense, or distribute generated documents as templates or products in your own service without written permission from Signova.</p>

        <h2>6. Limitation of liability</h2>
        <p>To the fullest extent permitted by law, Signova and its operators shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service or any document generated through it.</p>

        <h2>7. Changes to these terms</h2>
        <p>We may update these Terms from time to time. Continued use of the Service after changes are posted constitutes acceptance of the updated Terms.</p>

        <h2>8. Contact</h2>
        <p>Questions about these Terms? Email <a href={`mailto:${'info'}@${'ebenova.net'}`}>
          <span className="email-obfuscated" data-user="info" data-domain="ebenova.net"></span>
        </a>.</p>
      </div>
    </div>
  )
}
