import { useState } from 'react'
import { Helmet } from 'react-helmet-async'
import { useNavigate } from 'react-router-dom'
import {
  MapPin, Lightning, Robot, Lock, CheckCircle, XCircle, Warning,
} from '@phosphor-icons/react'
import './VigilLanding.css'

const HIW_ICON = { size: 24, weight: 'duotone', color: 'currentColor' }

const DEMO_CARDS = [
  { id: 'card_01', label: 'Calgary, CA — Home mode (50 km radius)', lat: 51.0447, lng: -114.0719, mode: 'home' },
  { id: 'card_02', label: 'Toronto → London — Travel mode', lat: 51.5074, lng: -0.1278, mode: 'travel' },
  { id: 'card_03', label: 'New York, US — Lockdown', lat: 40.7128, lng: -74.006, mode: 'lockdown' },
]

const DEMO_MERCHANTS = [
  { name: 'Safeway YYC', city: 'Calgary', country: 'CA', lat: 51.049, lng: -114.08, mcc: '5411', amount: 4250 },
  { name: 'Tesco London', city: 'London', country: 'GB', lat: 51.5, lng: -0.12, mcc: '5411', amount: 1850 },
  { name: 'Best Buy NYC', city: 'New York', country: 'US', lat: 40.75, lng: -73.99, mcc: '5732', amount: 89900 },
  { name: 'Amazon Nigeria', city: 'Lagos', country: 'NG', lat: 6.524, lng: 3.379, mcc: '5999', amount: 250000 },
]

const HOW_IT_WORKS = [
  { step: '01', icon: <MapPin {...HIW_ICON} />, title: 'Card knows your GPS', desc: 'Register your last-known location. Home radius: 50 km. Travel mode: covers declared countries. Lockdown: blocks everything.' },
  { step: '02', icon: <Lightning {...HIW_ICON} />, title: 'Transaction fires', desc: 'Merchant location + card GPS → haversine distance check in milliseconds. No external dependencies.' },
  { step: '03', icon: <Robot {...HIW_ICON} />, title: 'Claude scores the risk', desc: 'Claude Haiku analyzes velocity, MCC, distance, time-of-day patterns. Returns risk score 0–100 + SMS copy.' },
  { step: '04', icon: <Lock {...HIW_ICON} />, title: 'Approve or block', desc: 'You decide in real-time. Emergency lockdown via API. AML reports generated by Claude Sonnet for compliance.' },
]

const TIER_FEATURES = [
  { tier: 'Starter', price: '$29/mo', features: ['POST /v1/vigil/authorize', 'Risk score endpoint', '500 authorizations/month', 'Email support'] },
  { tier: 'Growth', price: '$79/mo', features: ['Everything in Starter', 'AI fraud analysis (Claude Haiku)', '2,000 authorizations/month', 'Priority support'], highlight: true },
  { tier: 'Scale', price: '$199/mo', features: ['Everything in Growth', 'AML compliance reports (Claude Sonnet)', '10,000 authorizations/month', 'SLA + dedicated support'] },
]

export default function VigilLanding() {
  const navigate = useNavigate()
  const [selectedCard, setSelectedCard] = useState(DEMO_CARDS[0])
  const [selectedMerchant, setSelectedMerchant] = useState(DEMO_MERCHANTS[0])
  const [result, setResult] = useState(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [copied, setCopied] = useState(false)

  async function handleDemo(e) {
    e.preventDefault()
    setError('')
    setResult(null)
    setLoading(true)
    try {
      const res = await fetch('/api/v1/vigil/authorize', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          card_id: selectedCard.id,
          merchant_name: selectedMerchant.name,
          merchant_city: selectedMerchant.city,
          merchant_country: selectedMerchant.country,
          merchant_lat: selectedMerchant.lat,
          merchant_lng: selectedMerchant.lng,
          merchant_mcc: selectedMerchant.mcc,
          amount_cents: selectedMerchant.amount,
          currency: selectedMerchant.country === 'NG' ? 'ngn' : selectedMerchant.country === 'GB' ? 'gbp' : 'cad',
        }),
      })
      const data = await res.json()
      if (!res.ok) { setError(data.error?.message || 'Request failed'); return }
      setResult(data)
    } catch {
      setError('Demo requires an API key. Sign up free at ebenova.dev/dashboard to test live.')
    } finally {
      setLoading(false)
    }
  }

  const curlSnippet = `curl -X POST https://api.ebenova.dev/v1/vigil/authorize \\
  -H "Authorization: Bearer sk_live_your_key" \\
  -H "Content-Type: application/json" \\
  -d '{
    "card_id": "card_01",
    "merchant_name": "Safeway",
    "merchant_city": "Calgary",
    "merchant_country": "CA",
    "merchant_lat": 51.049,
    "merchant_lng": -114.08,
    "amount_cents": 4250,
    "currency": "cad"
  }'`

  function handleCopy() {
    navigator.clipboard.writeText(curlSnippet)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <div className="vigil-page">
      <Helmet>
        <title>Vigil Fraud Alert API — Proximity-based card fraud detection | Ebenova</title>
        <meta name="description" content="Real-time card fraud detection using GPS proximity. Claude AI risk scoring 0–100. AML compliance reports. 8 MCP tools. Free tier available." />
        <link rel="canonical" href="https://www.ebenova.dev/vigil" />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://www.ebenova.dev/vigil" />
        <meta property="og:title" content="Vigil Fraud Alert API — GPS-powered card fraud detection" />
        <meta property="og:description" content="Real-time fraud detection using GPS proximity. Risk scoring 0–100. AML reports. 8 MCP tools. Free tier available." />
        <meta property="og:image" content="https://www.ebenova.dev/og-image.png" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="Vigil Fraud Alert API — GPS-powered card fraud detection" />
        <meta name="twitter:description" content="Detect card fraud in real time using GPS proximity. Claude AI risk scoring. 8 MCP tools. Free tier." />
        <meta name="twitter:image" content="https://www.ebenova.dev/og-image.png" />
      </Helmet>

      {/* Nav */}
      <nav className="vigil-nav">
        <div className="vigil-nav-inner">
          <div className="vigil-logo" onClick={() => navigate('/')}>
            <span className="vigil-logo-mark">E</span>
            <span className="vigil-logo-text">ebenova.dev</span>
          </div>
          <div className="vigil-nav-links">
            <a href="/">APIs</a>
            <a href="/docs">Docs</a>
            <a href="/dashboard" className="vigil-nav-cta">Get API Key — Free →</a>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <section className="vigil-hero">
        <div className="vigil-hero-glow" />
        <div className="vigil-hero-inner">
          <div className="vigil-badge">
            <span className="vigil-badge-dot" /> New · Live
          </div>
          <h1 className="vigil-hero-title">
            Your card was just used in Lagos.<br />
            <span className="vigil-accent">You&apos;re in Calgary.</span>
          </h1>
          <p className="vigil-hero-sub">
            Vigil blocks it before it clears. Proximity-based card authorization powered by GPS haversine engine + Claude AI risk scoring.
            8 MCP tools — Claude-native.
          </p>
          <div className="vigil-hero-actions">
            <button className="vigil-btn-primary" onClick={() => navigate('/dashboard')}>
              Get API Key — Free →
            </button>
            <button className="vigil-btn-outline" onClick={() => navigate('/docs')}>
              View API Docs
            </button>
          </div>
          <div className="vigil-trust">
            <span>✓ GPS haversine engine</span>
            <span>✓ Claude AI risk scoring</span>
            <span>✓ 8 MCP tools</span>
            <span>✓ No credit card required</span>
          </div>
        </div>
      </section>

      {/* Live Demo */}
      <section className="vigil-demo-section">
        <div className="vigil-section-inner">
          <div className="vigil-section-header">
            <p className="vigil-label">Live Demo</p>
            <h2 className="vigil-section-title">Run a real authorization</h2>
            <p className="vigil-section-sub">
              Uses the built-in proximity engine. <a href="/docs#vigil">See full API docs →</a>
            </p>
          </div>
          <form className="vigil-demo-form" onSubmit={handleDemo}>
            <div className="vigil-form-row">
              <div className="vigil-form-group">
                <label>Card profile</label>
                <select value={selectedCard.id} onChange={e => setSelectedCard(DEMO_CARDS.find(c => c.id === e.target.value))}>
                  {DEMO_CARDS.map(c => <option key={c.id} value={c.id}>{c.label}</option>)}
                </select>
              </div>
              <div className="vigil-form-group">
                <label>Merchant</label>
                <select value={selectedMerchant.name} onChange={e => setSelectedMerchant(DEMO_MERCHANTS.find(m => m.name === e.target.value))}>
                  {DEMO_MERCHANTS.map(m => <option key={m.name} value={m.name}>{m.name} — {m.city}, {m.country} ({m.amount / 100} {m.country === 'NG' ? 'NGN' : m.country === 'GB' ? 'GBP' : 'CAD'})</option>)}
                </select>
              </div>
            </div>
            <button className="vigil-btn-primary" type="submit" disabled={loading}>
              {loading ? 'Running authorization…' : <><Lightning size={16} weight="fill" style={{ verticalAlign: '-3px', marginRight: 6 }} />Run Authorization</>}
            </button>
          </form>
          {error && <div className="vigil-demo-error">{error}</div>}
          {result && (
            <div className={`vigil-demo-result ${result.approved || result.decision?.approved ? 'approved' : 'declined'}`}>
              <div className="vigil-result-header">
                <span className="vigil-result-icon">{result.approved || result.decision?.approved ? <CheckCircle size={20} weight="fill" /> : <XCircle size={20} weight="fill" />}</span>
                <span className="vigil-result-decision">{result.approved || result.decision?.approved ? 'APPROVED' : 'DECLINED'}</span>
                {(result.risk_score ?? result.decision?.risk_score) != null && (
                  <span className="vigil-result-risk">Risk: {result.risk_score ?? result.decision?.risk_score}/100</span>
                )}
              </div>
              {(result.distance_km ?? result.decision?.distance_km) != null && (
                <p className="vigil-result-detail"><MapPin size={14} weight="regular" style={{ verticalAlign: '-2px', marginRight: 4 }} />{result.distance_km ?? result.decision?.distance_km} km from home location</p>
              )}
              {(result.alert_id ?? result.decision?.alert_id) && (
                <p className="vigil-result-detail"><Warning size={14} weight="fill" style={{ verticalAlign: '-2px', marginRight: 4 }} />Fraud alert created: {result.alert_id ?? result.decision?.alert_id}</p>
              )}
              {result.reason && <p className="vigil-result-detail">Reason: {result.reason}</p>}
            </div>
          )}
        </div>
      </section>


      {/* How It Works */}
      <section className="vigil-how-section">
        <div className="vigil-section-inner">
          <div className="vigil-section-header">
            <p className="vigil-label">How it works</p>
            <h2 className="vigil-section-title">Four steps, milliseconds apart</h2>
          </div>
          <div className="vigil-steps-grid">
            {HOW_IT_WORKS.map(item => (
              <div key={item.step} className="vigil-step-card">
                <div className="vigil-step-num">{item.step}</div>
                <div className="vigil-step-icon">{item.icon}</div>
                <h3 className="vigil-step-title">{item.title}</h3>
                <p className="vigil-step-desc">{item.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Curl Snippet */}
      <section className="vigil-curl-section">
        <div className="vigil-section-inner vigil-curl-inner">
          <div className="vigil-curl-copy">
            <p className="vigil-label">Integration</p>
            <h2 className="vigil-section-title">One endpoint. Real‑time decisions.</h2>
            <p className="vigil-section-sub">
              Drop into your card issuing flow in under an hour. Works with any stack.
            </p>
            <ul className="vigil-curl-bullets">
              <li>POST /v1/vigil/authorize — GPS proximity decision</li>
              <li>POST /v1/vigil/analyze — Claude Haiku fraud analysis</li>
              <li>GET /v1/vigil/score?card_id= — live risk score</li>
              <li>POST /v1/vigil/report — Claude Sonnet AML report</li>
              <li>POST /v1/vigil/card — register and manage cards</li>
              <li>POST /v1/vigil/gps — submit device GPS location</li>
            </ul>
          </div>
          <div className="vigil-code-block">
            <div className="vigil-code-header">
              <span className="vigil-code-lang">curl</span>
              <button className="vigil-copy-btn" onClick={handleCopy}>
                {copied ? '✓ Copied' : 'Copy'}
              </button>
            </div>
            <pre className="vigil-code-pre"><code>{curlSnippet}</code></pre>
          </div>
        </div>
      </section>

      {/* Pricing */}
      <section className="vigil-pricing-section">
        <div className="vigil-section-inner">
          <div className="vigil-section-header">
            <p className="vigil-label">Pricing</p>
            <h2 className="vigil-section-title">Pay for what you protect</h2>
            <p className="vigil-section-sub">All plans use the same ebenova.dev API key. Upgrade anytime.</p>
          </div>
          <div className="vigil-pricing-grid">
            {TIER_FEATURES.map(tier => (
              <div key={tier.tier} className={`vigil-tier-card${tier.highlight ? ' highlighted' : ''}`}>
                {tier.highlight && <div className="vigil-tier-badge">Most Popular</div>}
                <h3 className="vigil-tier-name">{tier.tier}</h3>
                <div className="vigil-tier-price">{tier.price}</div>
                <ul className="vigil-tier-list">
                  {tier.features.map(f => <li key={f}><span>✓</span>{f}</li>)}
                </ul>
                <button
                  className={`vigil-btn-${tier.highlight ? 'primary' : 'outline'}`}
                  onClick={() => navigate('/dashboard')}
                >
                  Get started →
                </button>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* MCP Connector */}
      <section className="vigil-mcp-section">
        <div className="vigil-section-inner">
          <div className="vigil-mcp-inner">
            <div className="vigil-mcp-text">
              <p className="vigil-label">Claude-native</p>
              <h2 className="vigil-section-title">8 MCP tools. Works in Claude Desktop.</h2>
              <p className="vigil-section-sub">
                Add Vigil as a custom MCP connector in Claude Desktop and run fraud checks, travel plan updates,
                and AML reports directly in conversation — no code required.
              </p>
              <div className="vigil-mcp-config">
                <div className="vigil-code-header">
                  <span className="vigil-code-lang">claude_desktop_config.json</span>
                </div>
                <pre className="vigil-code-pre"><code>{`{
  "mcpServers": {
    "ebenova": {
      "url": "https://www.getsignova.com/mcp",
      "headers": {
        "Authorization": "Bearer sk_live_your_api_key"
      }
    }
  }
}`}</code></pre>
              </div>
            </div>
            <div className="vigil-mcp-tools">
              <p className="vigil-mcp-tools-label">Available MCP tools</p>
              {[
                'vigil_authorize','vigil_register_card','vigil_update_card',
                'vigil_submit_gps','vigil_get_risk_score','vigil_analyze_transaction',
                'vigil_generate_aml_report','vigil_emergency_lockdown',
              ].map(tool => (
                <div key={tool} className="vigil-tool-chip">{tool}</div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="vigil-footer">
        <div className="vigil-footer-inner">
          <div className="vigil-footer-brand">
            <span className="vigil-logo-mark">E</span>
            <span>ebenova.dev</span>
          </div>
          <div className="vigil-footer-links">
            <a href="/docs">Docs</a>
            <a href="/privacy">Privacy</a>
            <a href="/terms">Terms</a>
            <a href="/vigil/terms">Vigil Terms</a>
            <a href="mailto:hello@ebenova.dev">Contact</a>
          </div>
          <p className="vigil-footer-copy">© {new Date().getFullYear()} Ebenova Solutions Inc. All rights reserved.</p>
        </div>
      </footer>

    </div>
  )
}
