// api/v1/documents/generate.js
// POST https://api.ebenova.dev/v1/documents/generate
// Requires: Authorization: Bearer sk_live_...

import { authenticate, recordUsage, buildUsageBlock } from '../../../lib/api-auth.js'
import { DocumentGenerateSchema, formatValidationError } from '../../../lib/validators.js'
import { logError, logWarn, logRequest, logDetailedError } from '../../../lib/logger.js'
import { parseBody } from '../../../lib/parse-body.js'
import { buildDpaSystemPrompt, buildKeyObligationsSummary, buildDataFlowMappingTemplate, getDpaClauses } from './clauses.js'
import { buildJurisdictionContext } from '../../../lib/jurisdiction-context.js'
import { normalizeJurisdictionKey } from '../../../lib/jurisdiction-key-normalize.js'
import {
  generateWithCompletenessCheck,
  DOC_INCOMPLETE_AFTER_RETRY,
  DOC_TITLE_BODY_MISMATCH,
  DOC_FORBIDDEN_COMBINATION,
} from '../../../lib/doc-completeness.js'
import {
  hasDocType,
  isWorkerClassificationRequired,
  getWorkerClassificationModes,
} from '../../../lib/doc-registry.js'
import {
  validateWorkerClassification,
  buildClassificationInstruction,
  WORKER_CLASSIFICATION_REQUIRED,
  WORKER_CLASSIFICATION_INVALID,
} from '../../../lib/doc-classification.js'
import { randomBytes } from 'node:crypto'

const LEGAL_DISCLAIMER = {
  type: 'disclaimer',
  title: 'Legal Disclaimer',
  text: 'These documents are generated by AI and provided as templates for informational purposes only. They do not constitute legal advice. While we strive for accuracy, we make no guarantees regarding the completeness, accuracy, or suitability of these documents for your specific situation. Laws vary by jurisdiction and change frequently. You are strongly encouraged to consult with a qualified attorney licensed in your jurisdiction to review any document before use, execution, or reliance. Use of these documents is at your own risk, and neither Ebenova nor its creators assume any liability for damages arising from their use.',
  source: 'ebenova.dev',
}


function buildPrompt(docType, fields) {
  const fieldSummary = Object.entries(fields)
    .filter(([, v]) => v && (typeof v === 'string' ? v.trim() : true))
    .map(([k, v]) => {
      const display = Array.isArray(v) ? v.join(', ') : v
      const label = k.replace(/([A-Z])/g, ' $1').replace(/^./, s => s.toUpperCase())
      return `${label}: ${display}`
    })
    .join('\n')

  const docName = docType.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ')

  if (docType === 'data-processing-agreement') {
    const jurisdiction = fields.jurisdiction || 'Nigeria — NDPA 2023'
    const summary = buildKeyObligationsSummary(fields, jurisdiction)
    const dataFlow = buildDataFlowMappingTemplate(fields)
    return `Generate a Data Processing Agreement (DPA) for the following:

${fieldSummary}

The generated DPA must include THREE sections in this order:

SECTION 1 — KEY OBLIGATIONS SUMMARY (plain language, top of document):
${summary}

SECTION 2 — THE FORMAL DPA:
Write a comprehensive Data Processing Agreement with clear numbered sections. Include all standard DPA clauses tailored to the details provided. Use formal legal language but prioritise clarity — every obligation must state "Who," "What," and "When."

SECTION 3 — DATA FLOW MAPPING TEMPLATE (operational checklist):
${dataFlow}

Requirements:
- Do not include any placeholder text like [INSERT NAME] — use the actual values provided
- End with a signature block after Section 2 (before Section 3)
- Do NOT add any disclaimers, footnotes, notes, or suggestions to seek legal advice
- Output the complete document only, no preamble, explanation, or closing notes.`
  }

  return `Generate a professional, comprehensive ${docName} document for the following:

${fieldSummary}

Requirements:
- Write in formal legal language appropriate for the document type
- Be specific and detailed, not generic
- Structure with clear numbered sections and subsections
- Include all standard clauses expected in a ${docName}
- Tailor the content to the specific details provided
- Do not include any placeholder text like [INSERT NAME] — use the actual values provided
- End with a signature block
- Do NOT add any disclaimers, footnotes, notes, or suggestions to seek legal advice

Output the complete document only, no preamble, explanation, or closing notes.`
}

export default async function handler(req, res) {
  const startTime = Date.now()
  res.setHeader('Access-Control-Allow-Origin', '*')
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS')
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization')

  if (req.method === 'OPTIONS') return res.status(200).end()
  if (req.method !== 'POST') {
    return res.status(405).json({ success: false, error: { code: 'METHOD_NOT_ALLOWED', message: 'Use POST' } })
  }

  // ── Auth ──────────────────────────────────────────────────────────────────
  const auth = await authenticate(req)
  if (!auth.ok) {
    return res.status(auth.status).json({ success: false, error: auth.error })
  }

  // ── Parse + validate body with Zod ───────────────────────────────────────
  const body = await parseBody(req)
  
  let validated
  try {
    validated = DocumentGenerateSchema.parse(body)
  } catch (err) {
    logError('POST /v1/documents/generate', { 
      code: 'VALIDATION_ERROR',
      details: formatValidationError(err)
    })
    return res.status(400).json({ 
      success: false, 
      error: formatValidationError(err)
    })
  }

  const { document_type, fields, jurisdiction, worker_classification } = validated
  const enrichedFields = { ...fields, jurisdiction }

  // Phase 5 — worker_classification gate. REQUIRED when the doc_type has
  // registered modes. Invalid when submitted but not in the allowed set.
  // No silent default. Caller must supply an explicit value.
  if (isWorkerClassificationRequired(document_type)) {
    const validation = validateWorkerClassification(document_type, worker_classification)
    if (validation) {
      const refId = `ref_${randomBytes(4).toString('hex')}`
      const modes = getWorkerClassificationModes(document_type)
      logError('POST /v1/documents/generate', {
        reference_id: refId,
        code: validation.code,
        document_type,
        submitted_value: worker_classification || null,
        valid_values: modes,
        reason: validation.reason,
      })
      return res.status(400).json({
        success: false,
        error: {
          code: validation.code,
          message: validation.code === WORKER_CLASSIFICATION_REQUIRED
            ? `worker_classification is required for document_type="${document_type}"`
            : `worker_classification "${worker_classification}" is not valid for document_type="${document_type}"`,
          reference_id: refId,
          valid_values: modes,
        },
      })
    }
  }

  // Phase 4 — cross-check document_type against the registry. Zod has
  // already validated it against validators.js SUPPORTED_TYPES, but the
  // registry is the single source of truth for routing metadata. Log (do
  // not reject) if a supported doc_type isn't registered — keeps the
  // divergence observable while we migrate validators.js off its own list.
  if (!hasDocType(document_type)) {
    logWarn('POST /v1/documents/generate', {
      event: 'doc_type_not_in_registry',
      document_type,
      message: 'document_type passed Zod enum but is not in the doc-registry — registry is out of sync with validators.js',
    })
  }

  // ── Generate ──────────────────────────────────────────────────────────────
  const anthropicKey = process.env.ANTHROPIC_API_KEY
  if (!anthropicKey) {
    logError('POST /v1/documents/generate', { 
      code: 'SERVER_MISCONFIGURED',
      message: 'ANTHROPIC_API_KEY not set'
    })
    return res.status(500).json({ success: false, error: { code: 'SERVER_ERROR', message: 'Server misconfigured' } })
  }

  const prompt = buildPrompt(document_type, enrichedFields)

  try {
    const controller = new AbortController()
    // 280s timeout (5s headroom under Vercel's 300s function ceiling on Fluid
    // Compute). Previously 90s, which started producing 504s on API Market
    // after the jurisdiction-aware prompt expanded to 46 clauses — Claude
    // Sonnet 4.6 for a full Nigerian tenancy / SAFE can easily run 100-180s.
    const timeoutId = setTimeout(() => controller.abort(), 280000)

    // ── Jurisdiction-aware enhancement (non-DPA docs) ─────────────────────
    // jurisdiction comes from a validated field, so matching is safe without pronoun worries.
    const jurRaw = String(fields.jurisdiction || jurisdiction || '')
    const jurLower = jurRaw.toLowerCase()

    // Normalize to a canonical JURISDICTION_KEYS key for the library.
    // Falls back to null when unrecognised — the library's Commonwealth fallback
    // fires in buildJurisdictionContext() in that case; we do NOT inject an
    // unknown-jurisdiction block into non-DPA prompts.
    const normalizedJurKey = normalizeJurisdictionKey(jurRaw)
    if (jurRaw && !normalizedJurKey) {
      console.warn('[jurisdiction] Unknown key, using default:', jurRaw)
    }

    // Inline supplementary enhancements — kept as additional detail after the
    // library block for Quebec, Canada, California, and US-generic.
    // These fire for the same jurisdictions already handled by the library but
    // add product-specific notes (language-choice clause, non-compete void
    // notice) that the shared library intentionally omits to stay compact.
    const isQuebecJur = jurLower.includes('quebec') || jurLower.includes('québec') || jurLower.includes('law 25')
    const isCanadaJur = !isQuebecJur && (jurLower.includes('canada') || jurLower.includes('pipeda') ||
      /\b(ontario|british columbia|alberta|manitoba|saskatchewan|nova scotia|new brunswick|newfoundland|prince edward island|yukon|nunavut|northwest territories)\b/.test(jurLower))
    const isCaliforniaJur = jurLower.includes('california') || jurLower.includes('ccpa') || jurLower.includes('cpra')
    const isUSAJur = !isCaliforniaJur && (
      jurLower.includes('united states') ||
      /\b(USA|U\.S\.A\.|U\.S\.)\b/.test(jurRaw) ||
      /\b(alabama|alaska|arizona|arkansas|colorado|connecticut|delaware|florida|georgia|hawaii|idaho|illinois|indiana|iowa|kansas|kentucky|louisiana|maine|maryland|massachusetts|michigan|minnesota|mississippi|missouri|montana|nebraska|nevada|new hampshire|new jersey|new mexico|new york|north carolina|north dakota|ohio|oklahoma|oregon|pennsylvania|rhode island|south carolina|south dakota|tennessee|texas|utah|vermont|virginia|washington|west virginia|wisconsin|wyoming)\b/.test(jurLower)
    )

    let jurisdictionEnhancement = ''
    if (isQuebecJur) {
      jurisdictionEnhancement = '\n\nQUEBEC JURISDICTION: Apply Quebec Law 25, the Civil Code of Québec (reference CCQ articles, not common-law doctrine), and the Charter of the French Language. Use CAD currency. Include a language-choice clause.'
    } else if (isCanadaJur) {
      jurisdictionEnhancement = '\n\nCANADIAN JURISDICTION: Apply PIPEDA (privacy), CASL (commercial electronic messages), the applicable provincial Employment Standards Act for employment clauses, the Competition Act and provincial Consumer Protection Acts for B2C matters, and the Sale of Goods Act for commercial dealings. Use Canadian spelling and CAD currency. Name the specific province and its courts in governing-law/venue clauses.'
    } else if (isCaliforniaJur) {
      jurisdictionEnhancement = '\n\nCALIFORNIA JURISDICTION: Apply CCPA/CPRA for personal-information handling, California Labor Code for employment (note: post-employment non-competes are void under Bus. & Prof. Code §16600 — do not include), the CLRA for consumer terms, and the California Commercial Code for goods. Name a specific California county for venue. Use USD.'
    } else if (isUSAJur) {
      jurisdictionEnhancement = '\n\nUS JURISDICTION: Apply the UCC as adopted in the specified state for goods, the Restatement (Second) of Contracts for common-law doctrine, the applicable state data-breach notification statute, state comprehensive privacy laws (VCDPA, CPA, CTDPA, UCPA, TDPSA) where applicable, CAN-SPAM for commercial email, and the Federal Arbitration Act for arbitration clauses. Draft non-competes narrowly (duration, geography, legitimate protectable interest) and note states where they are restricted or void (CA, ND, OK). Name specific state and federal judicial district. Use USD.'
    }

    // Nigerian NDA — NDPA/GAID compliance overlay. Fires when document_type is 'nda'
    // and jurisdiction normalises to 'nigeria'. Mirrors nigeriaNDAClause in
    // api/generate.js — keep both in sync when updating clause content.
    const isNigerianNDA = document_type === 'nda' && normalizedJurKey === 'nigeria'
    const v1NigeriaNDAClause = isNigerianNDA
      ? '\n\nIMPORTANT — NIGERIAN NDA / CONFIDENTIALITY LAW: Apply:\n' +
        '(i) NO STANDALONE TRADE-SECRET STATUTE — Nigeria does not have a dedicated trade-secrets act. Protection flows from (a) CONTRACT (the NDA itself), (b) EQUITABLE DOCTRINE OF BREACH OF CONFIDENCE (Coco v A.N. Clark (Engineers) [1969] RPC 41 applied by Nigerian courts), and (c) the implied equitable duty of confidence in fiduciary and employment relationships.\n' +
        '(ii) GAID 2025 PRIMACY / NDPA 2023 OVERLAY — GAID 2025 is the primary binding regulatory directive for data processing in Nigeria; NDPA 2023 is the underlying Act which GAID 2025 implements. Where "Confidential Information" includes personal data of third parties, both instruments apply concurrently: lawful basis [GAID 2025 (implementing NDPA 2023 s.25 [VERIFY])], data-subject rights [GAID 2025 (implementing NDPA 2023 s.34 [VERIFY])], cross-border transfer restrictions [GAID 2025 (implementing NDPA 2023 s.43 [VERIFY])]. The NDA should NOT purport to override data-subject rights by contract.\n' +
        '(iii) NIGERIAN AUTHORITIES — Adetoun Oladeji (Nig.) Ltd v N.B. Plc [2007] 5 NWLR (Pt.1027) 415 (Supreme Court on breach of confidence); Rabiu v AG Kaduna [1980] 8–11 SC 130; Microfeed Nigeria v Gov. of Kano State for confidential-information principles in commercial context.\n' +
        '(iv) REASONABLE DURATION — perpetual confidentiality obligations are enforceable where the information genuinely remains a trade secret; but where the information enters the public domain, the obligation falls away (absent contract to the contrary). Typical drafted duration: 3–5 years for ordinary business info; indefinite for trade secrets.\n' +
        '(v) NON-SOLICITATION / NON-DEALING — clauses restraining post-NDA solicitation of employees or customers are subject to the restraint-of-trade doctrine — must be reasonable in scope and duration (see Koumoulis v Leventis Motors).\n' +
        '(vi) REMEDIES — injunction (prohibitory and mandatory), damages (measured as loss of business / account of profits / unjust enrichment), delivery-up of materials.\n' +
        '(vii) DISPUTE RESOLUTION — Arbitration and Mediation Act 2023 is the current framework (repealed the Arbitration and Conciliation Act 2004). Reference AMA 2023 with Lagos seat for most commercial NDAs.\n' +
        '(viii) STAMP DUTY — NDAs are dutiable at a nominal rate as "agreements under hand" per Stamp Duties Act Sch.1.\n' +
        '\n\nNIGERIAN NDA — NDPA/GAID COMPLIANCE REQUIREMENTS (REVIEWED BY DATALEX CONSULTING)\n' +
        'The following 9 requirements are MANDATORY. Each must appear as a distinct, substantive clause in the generated NDA. A clause heading alone is NOT sufficient — each clause must contain operative obligations. Do not skip, summarise, or weaken any of these requirements.\n\n' +
        '1. LAWFUL BASIS FOR PROCESSING — MANDATORY\n' +
        '(a) The "Personal Data" definition MUST incorporate the full definition from NDPA 2023 Section 65 [VERIFY], covering any information relating to an identified or identifiable natural person, including information usable alone or in combination to identify a person.\n' +
        '(b) A SEPARATE "Sensitive Personal Data" sub-category MUST be defined per GAID 2025 (implementing NDPA 2023 Section 30 [VERIFY]), covering: genetic data, biometric data, health data, racial or ethnic origin, religious or philosophical beliefs, political opinions, trade union membership, sexual orientation.\n' +
        '(c) A dedicated clause titled "Lawful Basis for Processing" MUST require each party to: (i) declare in writing the specific lawful basis relied upon BEFORE processing any personal data shared under this Agreement; (ii) select the basis from those recognised under GAID 2025 (implementing NDPA 2023 Section 25 [VERIFY]): consent, contract performance, legal obligation, vital interests of the data subject, public interest, or legitimate interests; (iii) maintain written documentation of the chosen basis for regulatory inspection.\n\n' +
        '2. DATA MINIMISATION — MANDATORY\n' +
        'A dedicated clause titled "Data Minimisation" MUST: (a) expressly restrict any personal data shared under this Agreement to only what is strictly necessary to fulfil the defined Purpose; (b) prohibit collection, processing, or retention of personal data beyond that scope; (c) cite GAID 2025 (implementing NDPA 2023 Section 24(1)(c) [VERIFY]) as the statutory authority.\n\n' +
        '3. DATA RETENTION AND DELETION — MANDATORY\n' +
        'A dedicated clause titled "Data Retention and Deletion" MUST: (a) specify the retention period: personal data shall be retained for the duration of this Agreement plus 2 years where legally required, or 30 days following fulfilment of the Purpose, whichever is the shorter period [VERIFY with Rosemary — she will confirm the final recommended default]; (b) require secure deletion OR irreversible anonymisation of all personal data upon expiry of the retention period; (c) require written confirmation of deletion or anonymisation within 14 days of a request from the disclosing party; (d) cite the GAID 2025 retention directive as the primary authority.\n\n' +
        '4. SECURITY MEASURES (TECHNICAL AND ORGANISATIONAL) — MANDATORY\n' +
        'Replace any vague "appropriate security measures" language. A dedicated clause titled "Technical and Organisational Security Measures" MUST specify: (a) encryption of all personal data using industry-standard algorithms such as AES-256 or equivalent, applied both at rest and in transit; (b) role-based access controls with documented authorisation lists, restricting access to personal data to personnel who require it solely to fulfil the Purpose; (c) internal data governance processes including incident logging, access audit trails, and periodic (at minimum annual) compliance reviews; (d) an obligation to maintain these measures for the duration of the Agreement and the applicable retention period; (e) cite GAID 2025 (implementing NDPA 2023 Section 39 [VERIFY]) as the source of this obligation.\n\n' +
        '5. DATA SUBJECT RIGHTS — MANDATORY\n' +
        'A dedicated clause titled "Data Subject Rights" MUST: (a) acknowledge and give effect to the rights under GAID 2025 (implementing NDPA 2023 Sections 33–38 [VERIFY]): right of access, right to rectification, right to erasure, right to object, and right to data portability; (b) require each party to facilitate the exercise of these rights in relation to personal data for which it is responsible under this Agreement; (c) confirm each data subject\'s right to lodge a complaint with the Nigeria Data Protection Commission (NDPC); (d) require each party to respond to data subject requests within 30 days of receipt; (e) designate a named contact point at each party responsible for handling data subject requests.\n\n' +
        '6. AUDIT AND COMPLIANCE VERIFICATION — MANDATORY\n' +
        'A dedicated clause titled "Audit and Compliance Verification" MUST: (a) entitle each party to request, at any time, written evidence of the other party\'s compliance with its GAID 2025 and NDPA 2023 obligations under this Agreement; (b) entitle each party to conduct a reasonable compliance audit, or to accept an equivalent independent third-party audit report in lieu; (c) require 14 calendar days\' prior written notice before any audit; (d) provide that each party bears its own audit costs unless the audit reveals a material breach, in which case the breaching party bears the reasonable and documented costs of the audit.\n\n' +
        '7. CROSS-BORDER DATA TRANSFER — GAID 2025 SAFEGUARDS — MANDATORY\n' +
        'The cross-border transfer clause MUST be expanded to include: (a) a declaration that GAID 2025 is the primary framework governing international transfers of personal data originating from Nigeria; (b) a requirement that any transfer of personal data outside Nigeria must rely on one of: (i) an adequacy determination by the NDPC, (ii) binding contractual safeguards such as standard data transfer clauses, or (iii) where neither applies, the explicit and informed written consent of the affected data subjects; (c) an obligation to notify affected data subjects of any international transfer, including the destination country and the transfer mechanism used.\n\n' +
        '8. BREACH NOTIFICATION HIERARCHY — MANDATORY\n' +
        'The breach-notification clause MUST be structured as a TWO-STEP hierarchy:\n' +
        'STEP 1 — PARTY-TO-PARTY NOTIFICATION (IMMEDIATE, BEFORE REGULATORY REPORTING): Upon discovery of any actual or reasonably suspected personal data breach affecting data processed under this Agreement, the discovering party MUST notify the other party in writing within 24 hours of discovery, and in any event BEFORE making any regulatory notification. The notice MUST include: (i) the nature of the breach; (ii) the categories and approximate number of personal data records affected; (iii) the estimated number of data subjects affected; (iv) the remediation steps taken or proposed.\n' +
        'STEP 2 — REGULATORY NOTIFICATION (72-HOUR NDPC OBLIGATION — RETAIN): RETAIN the obligation to notify the NDPC within 72 hours of becoming aware of a personal data breach, as required by GAID 2025 (implementing NDPA 2023 Section 40 [VERIFY]). Do NOT reduce, limit, or remove this obligation.\n\n' +
        '9. CONFIDENTIALITY DURATION AND DATA PROTECTION SURVIVAL — MANDATORY\n' +
        'The confidentiality duration clause MUST: (a) specify the confidentiality period explicitly: obligations of confidentiality shall continue for 3 years from the date of termination or expiry of this Agreement, or such longer period as required by applicable law [VERIFY with Rosemary — she will set the final recommended default]; (b) include an express survival clause: data protection obligations (lawful basis, data minimisation, security measures, data subject rights, audit rights, cross-border transfer safeguards, and breach notification) SURVIVE termination or expiry of this Agreement for the full duration of the applicable retention period; (c) cite GAID 2025 (implementing NDPA 2023 Section 41 [VERIFY]) as the source of continuing post-termination obligations.\n\n' +
        'This Nigerian NDA has been reviewed for NDPA 2023 / GAID 2025 compliance gaps by DataLex Consulting (Barrister Rosemary Onu-Okeke, Esq. LL.B, B.L, MSc). Every instruction above is MANDATORY. Do not skip, summarise, or weaken any of the 9 numbered requirements. Where [VERIFY] tags appear, retain the exact statute citation provided — do NOT invent or substitute section numbers. Non-compliance with NDPA 2023 data protection obligations exposes parties to regulatory penalties under GAID 2025 (implementing NDPA 2023 Section 48 [VERIFY]) of up to ₦10,000,000 or 2% of annual gross revenue, whichever is greater.\n' +
        'Governing law: Laws of the Federal Republic of Nigeria. Jurisdiction: Federal High Court (IP / confidential-information disputes relating to patents/copyright) or State High Court (pure contract / equity).'
      : ''

    // Build the library-backed jurisdiction context block (non-DPA only).
    // Prepended before the generic system prompt so Claude reads the authoritative
    // statutory framework first — same pattern as api/v1/scope/analyze.js.
    // DPA documents use buildDpaSystemPrompt() which has its own jurisdiction
    // handling; do not inject a second jurisdiction block there.
    const libraryJurContext = document_type !== 'data-processing-agreement' && normalizedJurKey
      ? buildJurisdictionContext(normalizedJurKey) + '\n\nWhen drafting this document, apply the jurisdiction framework above: cite the statutes listed where they bear on the document type; use the governing-law clause structure from the framework; use the forum/venue from the framework; use the currency from the framework for monetary references; do not invoke statutes from other jurisdictions.'
      : ''

    const systemPrompt = document_type === 'data-processing-agreement'
      ? buildDpaSystemPrompt(fields.jurisdiction) + '\n\nThis is a premium paid document — make it exceptional.'
      : (libraryJurContext ? libraryJurContext + '\n\n' : '')
        + 'You are an expert legal document drafter with deep knowledge of international law, including common-law (Canada, US, UK, Commonwealth), civil-law (Quebec), and the North American statutory privacy regimes (PIPEDA, Quebec Law 25, CCPA/CPRA). Generate comprehensive, professional legal documents tailored precisely to the details provided. Use formal legal language, clear numbered sections, and include all standard clauses. Use the spelling conventions of the governing jurisdiction. This is a premium paid document — make it exceptional. Never add disclaimers, footnotes, notes, or suggestions to consult a lawyer at the end of the document. The document ends cleanly after the signature block with no additional commentary.'
        + jurisdictionEnhancement
        + v1NigeriaNDAClause

    // Phase 3 — shared completeness-aware generator. Raises max_tokens
    // per-doctype from the spec, validates required clauses, continues
    // once if incomplete, fail-closes with DOC_INCOMPLETE_AFTER_RETRY
    // when the retry still fails. Same module consumed by api/generate.js
    // — no duplicated validator / continuation logic.
    // Phase 5 — build the classification routing instruction and inject
    // into the orchestrator. Empty string when the doc_type has no
    // classification config — orchestrator handles that gracefully.
    const classificationInstruction = buildClassificationInstruction(document_type, worker_classification)

    const completion = await generateWithCompletenessCheck({
      apiKey: anthropicKey,
      model: 'claude-sonnet-4-6',
      systemPrompt,
      userPrompt: prompt,
      docType: document_type,
      jurisdiction: fields.jurisdiction || jurisdiction || null,
      workerClassification: worker_classification || null,
      classificationInstruction,
      logger: { logWarn, logError },
      abortSignal: controller.signal,
    })
    clearTimeout(timeoutId)

    if (!completion.ok) {
      const errBody = {
        code: completion.code,
        reference_id: completion.referenceId,
      }
      if (completion.code === DOC_INCOMPLETE_AFTER_RETRY) {
        errBody.message = 'Document generation did not produce a complete document after continuation retry.'
        errBody.missing_clauses = completion.missingClauses
      } else if (completion.code === DOC_TITLE_BODY_MISMATCH) {
        errBody.message = 'Generated document body declares a different document type than requested.'
        errBody.expected_title = completion.expectedTitle
        errBody.conflicting_title = completion.conflictingTitle
      } else if (completion.code === DOC_FORBIDDEN_COMBINATION) {
        errBody.message = 'Generated document contains a legally incoherent combination of clauses (e.g. worker-exemption invoked alongside employee statutory deductions).'
        errBody.combination_id = completion.combinationId
        errBody.description = completion.description
        errBody.anchor_hits = completion.anchorHits
      } else {
        errBody.message = 'Document generation failed.'
      }
      return res.status(502).json({ success: false, error: errBody })
    }

    const documentText = completion.text

    // Record usage only after successful generation
    await recordUsage(auth)

    logRequest('POST /v1/documents/generate', 'POST', 200, Date.now() - startTime, { 
      document_type,
      tier: auth.keyData?.tier,
    })

    return res.status(200).json({
      success: true,
      document_type,
      document: documentText,
      disclaimer: LEGAL_DISCLAIMER,
      usage: buildUsageBlock(auth),
      generated_at: new Date().toISOString(),
    })
  } catch (err) {
    if (err.name === 'AbortError') {
      logError('POST /v1/documents/generate', {
        code: 'ANTHROPIC_TIMEOUT',
        message: 'Anthropic API request timed out after 90s',
        document_type,
      })
      return res.status(504).json({
        success: false,
        error: {
          code: 'GENERATION_TIMEOUT',
          message: 'Document generation timed out. Please try again.',
        },
      })
    }
    logDetailedError('POST /v1/documents/generate', err, {
      document_type,
      tier: auth.keyData?.tier,
    })
    return res.status(500).json({ success: false, error: { code: 'GENERATION_FAILED', message: 'Document generation failed. Please try again.' } })
  }
}
