// api/v1/documents/generate.js
// POST https://api.ebenova.dev/v1/documents/generate
// Requires: Authorization: Bearer sk_live_...

import { authenticate, recordUsage, buildUsageBlock } from '../../../lib/api-auth.js'
import { DocumentGenerateSchema, formatValidationError } from '../../../lib/validators.js'
import { logError, logRequest, logDetailedError } from '../../../lib/logger.js'
import { parseBody } from '../../../lib/parse-body.js'

const LEGAL_DISCLAIMER = {
  type: 'disclaimer',
  title: 'Legal Disclaimer',
  text: 'These documents are generated by AI and provided as templates for informational purposes only. They do not constitute legal advice. While we strive for accuracy, we make no guarantees regarding the completeness, accuracy, or suitability of these documents for your specific situation. Laws vary by jurisdiction and change frequently. You are strongly encouraged to consult with a qualified attorney licensed in your jurisdiction to review any document before use, execution, or reliance. Use of these documents is at your own risk, and neither Ebenova nor its creators assume any liability for damages arising from their use.',
  source: 'ebenova.dev',
}

function buildPrompt(docType, fields) {
  const fieldSummary = Object.entries(fields)
    .filter(([, v]) => v && (typeof v === 'string' ? v.trim() : true))
    .map(([k, v]) => {
      const display = Array.isArray(v) ? v.join(', ') : v
      const label = k.replace(/([A-Z])/g, ' $1').replace(/^./, s => s.toUpperCase())
      return `${label}: ${display}`
    })
    .join('\n')

  const docName = docType.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ')

  return `Generate a professional, comprehensive ${docName} document for the following:

${fieldSummary}

Requirements:
- Write in formal legal language appropriate for the document type
- Be specific and detailed, not generic
- Structure with clear numbered sections and subsections
- Include all standard clauses expected in a ${docName}
- Tailor the content to the specific details provided
- Do not include any placeholder text like [INSERT NAME] — use the actual values provided
- End with a signature block
- Do NOT add any disclaimers, footnotes, notes, or suggestions to seek legal advice

Output the complete document only, no preamble, explanation, or closing notes.`
}

export default async function handler(req, res) {
  const startTime = Date.now()
  res.setHeader('Access-Control-Allow-Origin', '*')
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS')
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization')

  if (req.method === 'OPTIONS') return res.status(200).end()
  if (req.method !== 'POST') {
    return res.status(405).json({ success: false, error: { code: 'METHOD_NOT_ALLOWED', message: 'Use POST' } })
  }

  // ── Auth ──────────────────────────────────────────────────────────────────
  const auth = await authenticate(req)
  if (!auth.ok) {
    return res.status(auth.status).json({ success: false, error: auth.error })
  }

  // ── Parse + validate body with Zod ───────────────────────────────────────
  const body = await parseBody(req)
  
  let validated
  try {
    validated = DocumentGenerateSchema.parse(body)
  } catch (err) {
    logError('POST /v1/documents/generate', { 
      code: 'VALIDATION_ERROR',
      details: formatValidationError(err)
    })
    return res.status(400).json({ 
      success: false, 
      error: formatValidationError(err)
    })
  }

  const { document_type, fields, jurisdiction } = validated
  const enrichedFields = { ...fields, jurisdiction }

  // ── Generate ──────────────────────────────────────────────────────────────
  const anthropicKey = process.env.ANTHROPIC_API_KEY
  if (!anthropicKey) {
    logError('POST /v1/documents/generate', { 
      code: 'SERVER_MISCONFIGURED',
      message: 'ANTHROPIC_API_KEY not set'
    })
    return res.status(500).json({ success: false, error: { code: 'SERVER_ERROR', message: 'Server misconfigured' } })
  }

  const prompt = buildPrompt(document_type, enrichedFields)

  try {
    const controller = new AbortController()
    const timeoutId = setTimeout(() => controller.abort(), 90000) // 90s timeout

    const response = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': anthropicKey,
        'anthropic-version': '2023-06-01',
      },
      body: JSON.stringify({
        model: 'claude-sonnet-4-5-20250929',
        max_tokens: 4000,
        system:
          'You are an expert legal document drafter with deep knowledge of international law. Generate comprehensive, professional legal documents tailored precisely to the details provided. Use formal legal language, clear numbered sections, and include all standard clauses. Never add disclaimers, footnotes, notes, or suggestions to consult a lawyer at the end of the document. The document ends cleanly after the signature block with no additional commentary.',
        messages: [{ role: 'user', content: prompt }],
      }),
      signal: controller.signal,
    })
    clearTimeout(timeoutId)

    if (!response.ok) {
      const err = await response.json()
      logDetailedError('POST /v1/documents/generate', new Error('Anthropic API error'), { 
        anthropic_response: err,
        document_type,
      })
      return res.status(500).json({ success: false, error: { code: 'GENERATION_FAILED', message: 'Document generation failed' } })
    }

    const data = await response.json()
    const documentText = data.content[0]?.text || ''

    // Record usage only after successful generation
    await recordUsage(auth)

    logRequest('POST /v1/documents/generate', 'POST', 200, Date.now() - startTime, { 
      document_type,
      tier: auth.keyData?.tier,
    })

    return res.status(200).json({
      success: true,
      document_type,
      document: documentText,
      disclaimer: LEGAL_DISCLAIMER,
      usage: buildUsageBlock(auth),
      generated_at: new Date().toISOString(),
    })
  } catch (err) {
    if (err.name === 'AbortError') {
      logError('POST /v1/documents/generate', {
        code: 'ANTHROPIC_TIMEOUT',
        message: 'Anthropic API request timed out after 90s',
        document_type,
      })
      return res.status(504).json({
        success: false,
        error: {
          code: 'GENERATION_TIMEOUT',
          message: 'Document generation timed out. Please try again.',
        },
      })
    }
    logDetailedError('POST /v1/documents/generate', err, {
      document_type,
      tier: auth.keyData?.tier,
    })
    return res.status(500).json({ success: false, error: { code: 'GENERATION_FAILED', message: 'Document generation failed. Please try again.' } })
  }
}
