// api/v1/documents/generate.js
// POST https://api.ebenova.dev/v1/documents/generate
// Requires: Authorization: Bearer sk_live_...

import { authenticate, recordUsage, buildUsageBlock } from '../../../lib/api-auth.js'
import { DocumentGenerateSchema, formatValidationError } from '../../../lib/validators.js'
import { logError, logRequest, logDetailedError } from '../../../lib/logger.js'
import { parseBody } from '../../../lib/parse-body.js'
import { buildDpaSystemPrompt, buildKeyObligationsSummary, buildDataFlowMappingTemplate, getDpaClauses } from './clauses.js'

const LEGAL_DISCLAIMER = {
  type: 'disclaimer',
  title: 'Legal Disclaimer',
  text: 'These documents are generated by AI and provided as templates for informational purposes only. They do not constitute legal advice. While we strive for accuracy, we make no guarantees regarding the completeness, accuracy, or suitability of these documents for your specific situation. Laws vary by jurisdiction and change frequently. You are strongly encouraged to consult with a qualified attorney licensed in your jurisdiction to review any document before use, execution, or reliance. Use of these documents is at your own risk, and neither Ebenova nor its creators assume any liability for damages arising from their use.',
  source: 'ebenova.dev',
}

function buildPrompt(docType, fields) {
  const fieldSummary = Object.entries(fields)
    .filter(([, v]) => v && (typeof v === 'string' ? v.trim() : true))
    .map(([k, v]) => {
      const display = Array.isArray(v) ? v.join(', ') : v
      const label = k.replace(/([A-Z])/g, ' $1').replace(/^./, s => s.toUpperCase())
      return `${label}: ${display}`
    })
    .join('\n')

  const docName = docType.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ')

  if (docType === 'data-processing-agreement') {
    const jurisdiction = fields.jurisdiction || 'Nigeria — NDPA 2023'
    const summary = buildKeyObligationsSummary(fields, jurisdiction)
    const dataFlow = buildDataFlowMappingTemplate(fields)
    return `Generate a Data Processing Agreement (DPA) for the following:

${fieldSummary}

The generated DPA must include THREE sections in this order:

SECTION 1 — KEY OBLIGATIONS SUMMARY (plain language, top of document):
${summary}

SECTION 2 — THE FORMAL DPA:
Write a comprehensive Data Processing Agreement with clear numbered sections. Include all standard DPA clauses tailored to the details provided. Use formal legal language but prioritise clarity — every obligation must state "Who," "What," and "When."

SECTION 3 — DATA FLOW MAPPING TEMPLATE (operational checklist):
${dataFlow}

Requirements:
- Do not include any placeholder text like [INSERT NAME] — use the actual values provided
- End with a signature block after Section 2 (before Section 3)
- Do NOT add any disclaimers, footnotes, notes, or suggestions to seek legal advice
- Output the complete document only, no preamble, explanation, or closing notes.`
  }

  return `Generate a professional, comprehensive ${docName} document for the following:

${fieldSummary}

Requirements:
- Write in formal legal language appropriate for the document type
- Be specific and detailed, not generic
- Structure with clear numbered sections and subsections
- Include all standard clauses expected in a ${docName}
- Tailor the content to the specific details provided
- Do not include any placeholder text like [INSERT NAME] — use the actual values provided
- End with a signature block
- Do NOT add any disclaimers, footnotes, notes, or suggestions to seek legal advice

Output the complete document only, no preamble, explanation, or closing notes.`
}

export default async function handler(req, res) {
  const startTime = Date.now()
  res.setHeader('Access-Control-Allow-Origin', '*')
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS')
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization')

  if (req.method === 'OPTIONS') return res.status(200).end()
  if (req.method !== 'POST') {
    return res.status(405).json({ success: false, error: { code: 'METHOD_NOT_ALLOWED', message: 'Use POST' } })
  }

  // ── Auth ──────────────────────────────────────────────────────────────────
  const auth = await authenticate(req)
  if (!auth.ok) {
    return res.status(auth.status).json({ success: false, error: auth.error })
  }

  // ── Parse + validate body with Zod ───────────────────────────────────────
  const body = await parseBody(req)
  
  let validated
  try {
    validated = DocumentGenerateSchema.parse(body)
  } catch (err) {
    logError('POST /v1/documents/generate', { 
      code: 'VALIDATION_ERROR',
      details: formatValidationError(err)
    })
    return res.status(400).json({ 
      success: false, 
      error: formatValidationError(err)
    })
  }

  const { document_type, fields, jurisdiction } = validated
  const enrichedFields = { ...fields, jurisdiction }

  // ── Generate ──────────────────────────────────────────────────────────────
  const anthropicKey = process.env.ANTHROPIC_API_KEY
  if (!anthropicKey) {
    logError('POST /v1/documents/generate', { 
      code: 'SERVER_MISCONFIGURED',
      message: 'ANTHROPIC_API_KEY not set'
    })
    return res.status(500).json({ success: false, error: { code: 'SERVER_ERROR', message: 'Server misconfigured' } })
  }

  const prompt = buildPrompt(document_type, enrichedFields)

  try {
    const controller = new AbortController()
    const timeoutId = setTimeout(() => controller.abort(), 90000)

    // ── Jurisdiction-aware enhancement (non-DPA docs) ─────────────────────
    // jurisdiction comes from a validated field, so matching is safe without pronoun worries.
    const jurRaw = String(fields.jurisdiction || jurisdiction || '')
    const jurLower = jurRaw.toLowerCase()
    const isQuebecJur = jurLower.includes('quebec') || jurLower.includes('québec') || jurLower.includes('law 25')
    const isCanadaJur = !isQuebecJur && (jurLower.includes('canada') || jurLower.includes('pipeda') ||
      /\b(ontario|british columbia|alberta|manitoba|saskatchewan|nova scotia|new brunswick|newfoundland|prince edward island|yukon|nunavut|northwest territories)\b/.test(jurLower))
    const isCaliforniaJur = jurLower.includes('california') || jurLower.includes('ccpa') || jurLower.includes('cpra')
    const isUSAJur = !isCaliforniaJur && (
      jurLower.includes('united states') ||
      /\b(USA|U\.S\.A\.|U\.S\.)\b/.test(jurRaw) ||
      /\b(alabama|alaska|arizona|arkansas|colorado|connecticut|delaware|florida|georgia|hawaii|idaho|illinois|indiana|iowa|kansas|kentucky|louisiana|maine|maryland|massachusetts|michigan|minnesota|mississippi|missouri|montana|nebraska|nevada|new hampshire|new jersey|new mexico|new york|north carolina|north dakota|ohio|oklahoma|oregon|pennsylvania|rhode island|south carolina|south dakota|tennessee|texas|utah|vermont|virginia|washington|west virginia|wisconsin|wyoming)\b/.test(jurLower)
    )

    let jurisdictionEnhancement = ''
    if (isQuebecJur) {
      jurisdictionEnhancement = '\n\nQUEBEC JURISDICTION: Apply Quebec Law 25, the Civil Code of Québec (reference CCQ articles, not common-law doctrine), and the Charter of the French Language. Use CAD currency. Include a language-choice clause.'
    } else if (isCanadaJur) {
      jurisdictionEnhancement = '\n\nCANADIAN JURISDICTION: Apply PIPEDA (privacy), CASL (commercial electronic messages), the applicable provincial Employment Standards Act for employment clauses, the Competition Act and provincial Consumer Protection Acts for B2C matters, and the Sale of Goods Act for commercial dealings. Use Canadian spelling and CAD currency. Name the specific province and its courts in governing-law/venue clauses.'
    } else if (isCaliforniaJur) {
      jurisdictionEnhancement = '\n\nCALIFORNIA JURISDICTION: Apply CCPA/CPRA for personal-information handling, California Labor Code for employment (note: post-employment non-competes are void under Bus. & Prof. Code §16600 — do not include), the CLRA for consumer terms, and the California Commercial Code for goods. Name a specific California county for venue. Use USD.'
    } else if (isUSAJur) {
      jurisdictionEnhancement = '\n\nUS JURISDICTION: Apply the UCC as adopted in the specified state for goods, the Restatement (Second) of Contracts for common-law doctrine, the applicable state data-breach notification statute, state comprehensive privacy laws (VCDPA, CPA, CTDPA, UCPA, TDPSA) where applicable, CAN-SPAM for commercial email, and the Federal Arbitration Act for arbitration clauses. Draft non-competes narrowly (duration, geography, legitimate protectable interest) and note states where they are restricted or void (CA, ND, OK). Name specific state and federal judicial district. Use USD.'
    }

    const systemPrompt = document_type === 'data-processing-agreement'
      ? buildDpaSystemPrompt(fields.jurisdiction) + '\n\nThis is a premium paid document — make it exceptional.'
      : 'You are an expert legal document drafter with deep knowledge of international law, including common-law (Canada, US, UK, Commonwealth), civil-law (Quebec), and the North American statutory privacy regimes (PIPEDA, Quebec Law 25, CCPA/CPRA). Generate comprehensive, professional legal documents tailored precisely to the details provided. Use formal legal language, clear numbered sections, and include all standard clauses. Use the spelling conventions of the governing jurisdiction. This is a premium paid document — make it exceptional. Never add disclaimers, footnotes, notes, or suggestions to consult a lawyer at the end of the document. The document ends cleanly after the signature block with no additional commentary.' + jurisdictionEnhancement

    const response = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': anthropicKey,
        'anthropic-version': '2023-06-01',
      },
      body: JSON.stringify({
        model: 'claude-sonnet-4-6',
        max_tokens: 8000,
        system: systemPrompt,
        messages: [{ role: 'user', content: prompt }],
      }),
      signal: controller.signal,
    })
    clearTimeout(timeoutId)

    if (!response.ok) {
      const err = await response.json()
      logDetailedError('POST /v1/documents/generate', new Error('Anthropic API error'), { 
        anthropic_response: err,
        document_type,
      })
      return res.status(500).json({ success: false, error: { code: 'GENERATION_FAILED', message: 'Document generation failed' } })
    }

    const data = await response.json()
    const documentText = data.content[0]?.text || ''

    // Record usage only after successful generation
    await recordUsage(auth)

    logRequest('POST /v1/documents/generate', 'POST', 200, Date.now() - startTime, { 
      document_type,
      tier: auth.keyData?.tier,
    })

    return res.status(200).json({
      success: true,
      document_type,
      document: documentText,
      disclaimer: LEGAL_DISCLAIMER,
      usage: buildUsageBlock(auth),
      generated_at: new Date().toISOString(),
    })
  } catch (err) {
    if (err.name === 'AbortError') {
      logError('POST /v1/documents/generate', {
        code: 'ANTHROPIC_TIMEOUT',
        message: 'Anthropic API request timed out after 90s',
        document_type,
      })
      return res.status(504).json({
        success: false,
        error: {
          code: 'GENERATION_TIMEOUT',
          message: 'Document generation timed out. Please try again.',
        },
      })
    }
    logDetailedError('POST /v1/documents/generate', err, {
      document_type,
      tier: auth.keyData?.tier,
    })
    return res.status(500).json({ success: false, error: { code: 'GENERATION_FAILED', message: 'Document generation failed. Please try again.' } })
  }
}
