export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).end()

  const { docType, docName } = req.body
  const origin = req.headers.origin || 'https://getsignova.com'

  try {
    const response = await fetch('https://api.lemonsqueezy.com/v1/checkouts', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${process.env.LEMONSQUEEZY_API_KEY}`,
        'Content-Type': 'application/vnd.api+json',
        'Accept': 'application/vnd.api+json',
      },
      body: JSON.stringify({
        data: {
          type: 'checkouts',
          attributes: {
            checkout_data: {
              custom: { docType },
            },
            product_options: {
              name: docName,
              description: `Professional ${docName} — generated by Signova`,
              redirect_url: `${origin}/preview?payment=success`,
            },
            checkout_options: {
              dark: true,
            },
          },
          relationships: {
            store: {
              data: { type: 'stores', id: process.env.LEMONSQUEEZY_STORE_ID },
            },
            variant: {
              data: { type: 'variants', id: process.env.LEMONSQUEEZY_VARIANT_ID },
            },
          },
        },
      }),
    })

    if (!response.ok) {
      const err = await response.json()
      throw new Error(JSON.stringify(err))
    }

    const json = await response.json()
    const checkoutUrl = json.data.attributes.url

    res.status(200).json({ url: checkoutUrl })
  } catch (err) {
    console.error('Lemon Squeezy error:', err)
    res.status(500).json({ error: err.message })
  }
}
